UpSampling2D Layer

In [50]:
from numpy import asarray
from keras.models import Sequential
from keras.layers import UpSampling2D, Dense, Reshape, Conv2D, Conv2DTranspose

In [21]:
X = asarray([[1, 2],
			 [3, 4]])

In [22]:
print(X)

[[1 2]
 [3 4]]


In [23]:
X = X.reshape((1, 2, 2, 1))

In [36]:
model = Sequential()
model.add(UpSampling2D(input_shape=(2, 2, 1)))
# model.add(UpSampling2D(size=(2, 3)))
# model.add(UpSampling2D(interpolation='bilinear'))

In [37]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_8 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [38]:
yhat = model.predict(X)

In [39]:
yhat = yhat.reshape((4, 4))

In [40]:
print(yhat)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


Generator Model With UpSampling2D Layer

In [41]:
model = Sequential()

In [44]:
model.add(Dense(128 * 5 * 5, input_dim=100))

In [46]:
model.add(Reshape((5, 5, 128)))

In [47]:
model.add(UpSampling2D())

In [48]:
model.add(Conv2D(1, (3,3), padding='same'))

In [49]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3200)              323200    
_________________________________________________________________
reshape (Reshape)            (None, 5, 5, 128)         0         
_________________________________________________________________
reshape_1 (Reshape)          (None, 5, 5, 128)         0         
_________________________________________________________________
up_sampling2d_9 (UpSampling2 (None, 10, 10, 128)       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________


Conv2DTranspose Layer

In [51]:
X = asarray([[1, 2],
			 [3, 4]])

In [52]:
print(X)

[[1 2]
 [3 4]]


In [53]:
X = X.reshape((1, 2, 2, 1))

In [54]:
model = Sequential()
model.add(Conv2DTranspose(1, (1,1), strides=(2,2), input_shape=(2, 2, 1)))


In [55]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose (Conv2DTran (None, 4, 4, 1)           2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [56]:
weights = [asarray([[[[1]]]]), asarray([0])]

In [57]:
model.set_weights(weights)

In [58]:
yhat = model.predict(X)

In [59]:
yhat = yhat.reshape((4, 4))

In [60]:
print(yhat)

[[1. 0. 2. 0.]
 [0. 0. 0. 0.]
 [3. 0. 4. 0.]
 [0. 0. 0. 0.]]


Generator Model With Conv2DTranspose Layer

In [61]:
model = Sequential()

In [63]:
model.add(Dense(128 * 5 * 5, input_dim=100))

In [64]:
model.add(Reshape((5, 5, 128)))

In [65]:
model.add(Conv2DTranspose(1, (3,3), strides=(2,2), padding='same'))

In [66]:
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3200)              323200    
_________________________________________________________________
dense_2 (Dense)              (None, 3200)              10243200  
_________________________________________________________________
reshape_2 (Reshape)          (None, 5, 5, 128)         0         
_________________________________________________________________
conv2d_transpose_1 (Conv2DTr (None, 10, 10, 1)         1153      
Total params: 10,567,553
Trainable params: 10,567,553
Non-trainable params: 0
_________________________________________________________________
